version: '3.8'

services:
  mlflow:
    build:
      context: mlflow
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    environment:
      MLFLOW_TRACKING_URI: http://localhost:5000
      MLFLOW_BACKEND_STORE_URI: postgresql://mlflow_user:mlflow_pass@db/mlflow_db
      MLFLOW_ARTIFACT_ROOT: s3://mlflow/
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      MLFLOW_BASIC_AUTH_USERNAME: admin  # Set up basic auth username
      MLFLOW_BASIC_AUTH_PASSWORD: password  # Set up basic auth password
    depends_on:
      - db
      - minio
    command: mlflow server --backend-store-uri postgresql://mlflow_user:mlflow_pass@db/mlflow_db --default-artifact-root s3://mlflow/ --host 0.0.0.0 --app-name "basic-auth" --serve-artifacts

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: mlflow_user
      POSTGRES_PASSWORD: mlflow_pass
      POSTGRES_DB: mlflow_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data

volumes:
  pgdata:
  minio_data:
